### PR TITLE
fix: breadcrumb not jump

### PR DESCRIPTION
**Pull request by xiaoxian521**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [ ] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by anncwb** [comment]
其实改成这样主要是为了消灭 直接import router from '/@/router'的写法，这个写法热更新会出问题。这个bug我在看看怎么弄

**Comment by xiaoxian521** [comment]
ok

**Comment by xiaoxian521** [comment]
在useGo和useRedo传人两个参数，第二个参数是useRouter是不是可以避免这个问题呢

**Comment by anncwb** [comment]
应该是可以。router从外部传入

**Pull request closed without merging**
