### PR TITLE
[feat] try to implement vue-i18n for all app (need comments)

### PR DESCRIPTION
**Pull request by aios**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [ ] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [x] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by aios** [comment]
:confused: sorry it my first PR for this repo - i cant give 100% guarantee for making all clean.

**Comment by anncwb** [comment]
Thank you very much. I read it and it is very good. I may not merge at present because not many people need it. I will merge your code in a separate branch in a few days.

**Comment by anncwb** [comment]
After reading your code carefully, I think it works. I will implement it immediately when the project stabilizes

**Comment by aios** [comment]
@anncwb ty. i dont't find tests for accurate and evade bugs if you can tell me how i can run it - you can write here

**Comment by aios** [comment]
Maybe i can help with project stability? @anncwb

**Comment by anncwb** [comment]
Very welcome, because the current vue, vuex, vue-router, vite and other related supporting facilities are not perfect. So there is still a lot to modify

**Comment by aios** [comment]
@anncwb are you have some task board maybe?

**Comment by anncwb** [comment]
Because I am alone in maintaining this project, so I don't currently have it. I will create it shortly. You can also make some suggestions

**Comment by aios** [comment]
@anncwb if you can, give me direction and i will move

**Comment by anncwb** [comment]
ok。Give me some time to prepare

**Comment by aios** [comment]
@anncwb ok no problem - i think that project best sample to use ts + vue3 + i can make something for that, cause i need it ASAP

**Comment by anncwb** [comment]
@aios I am going to join the internationalization function these two days. Since there are so many changes, you may only learn from your ideas. This pull request may not be merged

**Comment by aios** [comment]
> @aios I am going to join the internationalization function these two days. Since there are so many changes, you may only learn from your ideas. This pull request may not be merged

Something not right? or may be need to add more comments - i surely can't understand where the mistake)

**Comment by anncwb** [comment]
1. I plan to use ts format files instead of json
2. Transform judges that the .json suffix file may affect other codes

I am now starting to integrate multiple languages

**Comment by aios** [comment]
@anncwb so i may to close - my pr? you will make it by other way ? or may be i can to refactor something for changes wich can help you to integrate that pr?

**Comment by anncwb** [comment]
I will release a version for trial tomorrow, and then you can put forward your suggestions

**Comment by aios** [comment]
Ok, will w8)

**Comment by aios** [comment]
@anncwb may be i can help with some part of that task?

**Pull request closed without merging**
