### PR TITLE
Fixing Code Quality Issues

### PR DESCRIPTION
**Pull request by HarshCasper**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [X] Pull request template structure not broken

### `Type`

> ℹ️ What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### `Checklist`

> ℹ️ Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](contributing.md).

> 👉 _Put an `x` in the boxes that apply._

- [ ] My code follows the style guidelines of this project
- [X] Is the code format correct
- [ ] Is the git submission information standard?
- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### Note

Hi 👋 

I ran the DeepSource static analyzer on the forked copy of this repo and found some interesting code quality [issues](https://deepsource.io/gh/HarshCasper/vue-vben-admin/). This PR fixes a few of them.

### CODE REVIEW

**Comment by JohnNiang** [comment]
This changes will greatly reduce code readability.

**Comment by anncwb** [comment]
Can you tell me the role of deepsource

**Comment by HarshCasper** [comment]
> This changes will greatly reduce code readability.

Usually, using an if-else statement typically results in more lines of code than a single-line ternary expression, which leads to an unnecessarily larger codebase that is more difficult to maintain.

Additionally, using an if-else statement can result in defining variables using let or var solely to be reassigned within the blocks. This leads to variables being unnecessarily mutable and prevents prefer-const from flagging the variable.

**Comment by HarshCasper** [comment]
> Can you tell me the role of deepsource？

Sure. 

DeepSource is one of the most popular tools for static analysis, providing tracking over 800+ potential issues, like unused variables, empty functions, usage of Script URLs, and more in JavaScript codebase.

DeepSource JavaScript analyzer currently supports a wide variety of Javascript libraries and frameworks like ReactJS, VueJS, AngularJS, Angular, Ember, and more, along with various ECMAScript versions and Typescript. If you are following a style guide, DeepSource provides support for that as well, along with the module system.

At its core, DeepSource strictly enforces ESLint core JavaScript rules, which allow us to identify bugs, anti-patterns, and non-performant code. 

It has a single-file configuration, the `.deepsource.toml` after which it provides an integrated dashboard for Code metrics tracking and reporting, analysis of every pull request and commit and highlighting important metrics like documentation coverage and dependency.

**Comment by anncwb** [comment]
My understanding may be a program similar to snoar

**Comment by JohnNiang** [comment]
IMO, those actions could be handled at building stage.

**Pull request closed without merging**
